disabled_rules:
  - multiple_closures_with_trailing_closure
  - line_length
  - force_unwrapping
opt_in_rules:
  - trailing_whitespace
  - todo
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - nimble_operator
  - no_extension_access_modifier
  - overridden_super_call
  - prohibited_super_call
  - override_in_extension
  - prefixed_toplevel_constant
  - private_over_fileprivate
  - strict_fileprivate
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
function_body_length:
  warning: 50
  error: 100
cyclomatic_complexity:
  warning: 20
  error: 100
force_try: warning 
force_cast: warning
